platform :ios, '13.0'

require_relative '../node_modules/react-native/scripts/react_native_pods'

target 'app-beytee' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => false
  )

  target 'app-beyteeTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    react_native_post_install(installer)
  end
end